// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupGhostedApplicatrions = `-- name: CleanupGhostedApplicatrions :exec
UPDATE job_applications
SET
  status = 1,
  date_updated = NOW()
WHERE (
  date_updated < NOW() - interval '1 week'
  OR date_updated IS NULL
)
AND status != 1
`

func (q *Queries) CleanupGhostedApplicatrions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupGhostedApplicatrions)
	return err
}

const createJobApplication = `-- name: CreateJobApplication :one
INSERT INTO job_applications(
  company, role, date_applied, status, owner_id, description, url, notes
) VALUES($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company, role, date_applied, date_updated, status, owner_id, description, url, notes
`

type CreateJobApplicationParams struct {
	Company     string             `json:"company"`
	Role        string             `json:"role"`
	DateApplied pgtype.Timestamptz `json:"date_applied"`
	Status      int32              `json:"status"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Description pgtype.Text        `json:"description"`
	Url         pgtype.Text        `json:"url"`
	Notes       pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateJobApplication(ctx context.Context, arg CreateJobApplicationParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, createJobApplication,
		arg.Company,
		arg.Role,
		arg.DateApplied,
		arg.Status,
		arg.OwnerID,
		arg.Description,
		arg.Url,
		arg.Notes,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.DateApplied,
		&i.DateUpdated,
		&i.Status,
		&i.OwnerID,
		&i.Description,
		&i.Url,
		&i.Notes,
	)
	return i, err
}

const deleteJobApplication = `-- name: DeleteJobApplication :exec
DELETE FROM job_applications
WHERE id=$1
`

func (q *Queries) DeleteJobApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobApplication, id)
	return err
}

const getJobApplications = `-- name: GetJobApplications :many
SELECT id, company, role, date_applied, date_updated, status, description, url, notes
FROM job_applications
WHERE owner_id=$1
`

type GetJobApplicationsRow struct {
	ID          uuid.UUID          `json:"id"`
	Company     string             `json:"company"`
	Role        string             `json:"role"`
	DateApplied pgtype.Timestamptz `json:"date_applied"`
	DateUpdated pgtype.Timestamptz `json:"date_updated"`
	Status      int32              `json:"status"`
	Description pgtype.Text        `json:"description"`
	Url         pgtype.Text        `json:"url"`
	Notes       pgtype.Text        `json:"notes"`
}

func (q *Queries) GetJobApplications(ctx context.Context, ownerID uuid.UUID) ([]GetJobApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getJobApplications, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobApplicationsRow
	for rows.Next() {
		var i GetJobApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.DateApplied,
			&i.DateUpdated,
			&i.Status,
			&i.Description,
			&i.Url,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobApplication = `-- name: UpdateJobApplication :one
UPDATE job_applications
SET
  company = $3,
  role = $4,
  status = $5,
  date_updated = NOW(),
  description = $6,
  url = $7,
  notes = $8
WHERE id=$1 AND owner_id=$2
RETURNING id, company, role, date_applied, date_updated, status, owner_id, description, url, notes
`

type UpdateJobApplicationParams struct {
	ID          uuid.UUID   `json:"id"`
	OwnerID     uuid.UUID   `json:"owner_id"`
	Company     string      `json:"company"`
	Role        string      `json:"role"`
	Status      int32       `json:"status"`
	Description pgtype.Text `json:"description"`
	Url         pgtype.Text `json:"url"`
	Notes       pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateJobApplication(ctx context.Context, arg UpdateJobApplicationParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, updateJobApplication,
		arg.ID,
		arg.OwnerID,
		arg.Company,
		arg.Role,
		arg.Status,
		arg.Description,
		arg.Url,
		arg.Notes,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.DateApplied,
		&i.DateUpdated,
		&i.Status,
		&i.OwnerID,
		&i.Description,
		&i.Url,
		&i.Notes,
	)
	return i, err
}

const updateJobApplicationStatus = `-- name: UpdateJobApplicationStatus :one
UPDATE job_applications
SET
  status = $3,
  date_updated = NOW()
WHERE id=$1 AND owner_id=$2
RETURNING id, company, role, date_applied, date_updated, status, owner_id, description, url, notes
`

type UpdateJobApplicationStatusParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
	Status  int32     `json:"status"`
}

func (q *Queries) UpdateJobApplicationStatus(ctx context.Context, arg UpdateJobApplicationStatusParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, updateJobApplicationStatus, arg.ID, arg.OwnerID, arg.Status)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.DateApplied,
		&i.DateUpdated,
		&i.Status,
		&i.OwnerID,
		&i.Description,
		&i.Url,
		&i.Notes,
	)
	return i, err
}
