// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createJobApplication = `-- name: CreateJobApplication :one
INSERT INTO job_applications(
  company, role, date_applied, status
) VALUES($1, $2, $3, $4)
RETURNING id, company, role, date_applied, date_updated, status, owner_id
`

type CreateJobApplicationParams struct {
	Company     string
	Role        string
	DateApplied time.Time
	Status      int32
}

func (q *Queries) CreateJobApplication(ctx context.Context, arg CreateJobApplicationParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, createJobApplication,
		arg.Company,
		arg.Role,
		arg.DateApplied,
		arg.Status,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.DateApplied,
		&i.DateUpdated,
		&i.Status,
		&i.OwnerID,
	)
	return i, err
}

const getJobApplications = `-- name: GetJobApplications :many
SELECT id, company, role, date_applied, date_updated, status
FROM job_applications
`

type GetJobApplicationsRow struct {
	ID          uuid.UUID
	Company     string
	Role        string
	DateApplied time.Time
	DateUpdated sql.NullTime
	Status      int32
}

func (q *Queries) GetJobApplications(ctx context.Context) ([]GetJobApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobApplicationsRow
	for rows.Next() {
		var i GetJobApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.DateApplied,
			&i.DateUpdated,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobApplication = `-- name: UpdateJobApplication :one
UPDATE job_applications
SET
  company = $2,
  role = $3,
  status = $4,
  date_updated = NOW()
WHERE id=$1
RETURNING id, company, role, date_applied, date_updated, status, owner_id
`

type UpdateJobApplicationParams struct {
	ID      uuid.UUID
	Company string
	Role    string
	Status  int32
}

func (q *Queries) UpdateJobApplication(ctx context.Context, arg UpdateJobApplicationParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, updateJobApplication,
		arg.ID,
		arg.Company,
		arg.Role,
		arg.Status,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.DateApplied,
		&i.DateUpdated,
		&i.Status,
		&i.OwnerID,
	)
	return i, err
}
