// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package repo

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const importJobApplications = `-- name: ImportJobApplications :batchone
INSERT INTO job_applications(
  company, role, date_applied, status, owner_id, description, url, notes
) VALUES($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company, role, date_applied, date_updated, status, owner_id, description, url, notes
`

type ImportJobApplicationsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ImportJobApplicationsParams struct {
	Company     string             `json:"company"`
	Role        string             `json:"role"`
	DateApplied pgtype.Timestamptz `json:"date_applied"`
	Status      int32              `json:"status"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Description pgtype.Text        `json:"description"`
	Url         pgtype.Text        `json:"url"`
	Notes       pgtype.Text        `json:"notes"`
}

func (q *Queries) ImportJobApplications(ctx context.Context, arg []ImportJobApplicationsParams) *ImportJobApplicationsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Company,
			a.Role,
			a.DateApplied,
			a.Status,
			a.OwnerID,
			a.Description,
			a.Url,
			a.Notes,
		}
		batch.Queue(importJobApplications, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ImportJobApplicationsBatchResults{br, len(arg), false}
}

func (b *ImportJobApplicationsBatchResults) QueryRow(f func(int, JobApplication, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i JobApplication
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.DateApplied,
			&i.DateUpdated,
			&i.Status,
			&i.OwnerID,
			&i.Description,
			&i.Url,
			&i.Notes,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *ImportJobApplicationsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
