// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type JobApplication struct {
	ID          uuid.UUID
	Company     string
	Role        string
	DateApplied time.Time
	DateUpdated sql.NullTime
	Status      int32
	OwnerID     uuid.UUID
}

type RefreshToken struct {
	ID    uuid.UUID
	Token string
}

type User struct {
	ID       uuid.UUID
	Email    string
	Password string
}
