// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type JobApplication struct {
	ID          uuid.UUID          `json:"id"`
	Company     string             `json:"company"`
	Role        string             `json:"role"`
	DateApplied pgtype.Timestamptz `json:"date_applied"`
	DateUpdated pgtype.Timestamptz `json:"date_updated"`
	Status      int32              `json:"status"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Description pgtype.Text        `json:"description"`
	Url         pgtype.Text        `json:"url"`
	Notes       pgtype.Text        `json:"notes"`
}

type RefreshToken struct {
	ID    uuid.UUID `json:"id"`
	Token string    `json:"token"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
}
