// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRefreshToken(ctx context.Context, token string) error
	CreateJobApplication(ctx context.Context, arg CreateJobApplicationParams) (JobApplication, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshToken(ctx context.Context, token string) error
	GetJobApplications(ctx context.Context, ownerID uuid.UUID) ([]GetJobApplicationsRow, error)
	GetRefreshToken(ctx context.Context, token string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateJobApplication(ctx context.Context, arg UpdateJobApplicationParams) (JobApplication, error)
}

var _ Querier = (*Queries)(nil)
