// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package repo

import (
	"context"
)

const addRefreshToken = `-- name: AddRefreshToken :exec
INSERT INTO refresh_tokens(token) VALUES($1)
`

func (q *Queries) AddRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, addRefreshToken, token)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token=$1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token FROM refresh_tokens WHERE token=$1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var token_2 string
	err := row.Scan(&token_2)
	return token_2, err
}
